# Generated by Django 5.1.7 on 2025-03-20 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('officer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('officer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('rank', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('attendance', models.IntegerField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('police_count', models.IntegerField()),
                ('patrol_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.officer')),
            ],
        ),
    ]
